workflows:
  ios_release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      groups:
        - app_store_connect

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Flutter clean
        script: flutter clean

      - name: Build IPA (no codesign here; Codemagic handles with integration)
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - flutter_drive.log
