workflows:
  ios_release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_connect

    scripts:
      - name: Set Flutter version
        script: |
          flutter --version
          flutter doctor

      - name: Flutter pub get
        script: flutter pub get

      - name: Flutter clean
        script: flutter clean

      - name: Clean iOS build artifacts
        script: |
          cd ios
          rm -rf Pods Podfile.lock .symlinks DerivedData
          cd ..

      - name: Install CocoaPods dependencies (CRITICAL for plugin setup)
        script: |
          cd ios
          pod repo update
          pod install --verbose
          cd ..

      - name: Build IPA (no codesign here; Codemagic handles with integration)
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - flutter_drive.log